// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdOSH0AbxaNYZj4NtK6WuL4PVoKrNnwlU',
    appId: '1:876012783823:web:980327be7206ad76280fba',
    messagingSenderId: '876012783823',
    projectId: 'smartcabinet-a190c',
    authDomain: 'smartcabinet-a190c.firebaseapp.com',
    databaseURL: 'https://smartcabinet-a190c-default-rtdb.firebaseio.com',
    storageBucket: 'smartcabinet-a190c.appspot.com',
    measurementId: 'G-C3K9Y6K1SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJvIGjOlQnF3Sz3XknTc8boixzD1x41qs',
    appId: '1:876012783823:android:d74fb55a09ecd60b280fba',
    messagingSenderId: '876012783823',
    projectId: 'smartcabinet-a190c',
    databaseURL: 'https://smartcabinet-a190c-default-rtdb.firebaseio.com',
    storageBucket: 'smartcabinet-a190c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHr_oCt9NWZTeTdKHoXNUNP9w0Y1X2GG0',
    appId: '1:876012783823:ios:4bf0f28d0c6ea21c280fba',
    messagingSenderId: '876012783823',
    projectId: 'smartcabinet-a190c',
    databaseURL: 'https://smartcabinet-a190c-default-rtdb.firebaseio.com',
    storageBucket: 'smartcabinet-a190c.appspot.com',
    iosClientId: '876012783823-o8jf8mom263od98fh2m6m152j1pgrb88.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApresentacao2',
  );
}
